name: Python package

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install mujoco-py dependencies
        run: |
          sudo apt install -y libosmesa6-dev libgl1-mesa-glx libglfw3
          eval "$(direnv hook bash)"
        shell: bash
      - name: Install with Poetry
        run: |
          export LD_LIBRARY_PATH=${PWD}/data/mujoco210/bin:/usr/lib/nvidia
          export MUJOCO_PY_MUJOCO_PATH=${PWD}/data/mujoco210
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
        shell: bash
      - name: Test with pytest
        run: |
          export LD_LIBRARY_PATH=${PWD}/data/mujoco210/bin:/usr/lib/nvidia
          export MUJOCO_PY_MUJOCO_PATH=${PWD}/data/mujoco210
          poetry run pytest
        shell: bash